### ISSUE TITLE
тут был отзыв на тестовое

### ISSUE THREAD

**Issue by manitunv** [g3co/playkot#1]
тут был отзыв и переписка, извиняюсь - решено удалить.

**Comment by g3co** [comment]
@manitu1983 

- По поводу преимуществ адаптеров. Хотелось полностью отделить работу с базой и подготовкой Payment. Соответственно через тот же адаптер можно сохранять и другие сущности.
- Баг с array_diff как я понимаю связан с неверным приведением типов и некоректным сравнением?
- Необходимости в лишних запросах нет (проверка существования и получение объекта), можно записать все поля сразу. Но чтобы вписаться в требования задачи с сохранением только изменённых полей, я не вижу другого выхода, кроме как сравнивать с хранимыми данными.
- Да маппер совсем не к месту в хэндлере, это не его область ответственности. Лучше было бы проверить в точке входа. Без использования маппера, наверное, что-то вроде 

`defined('State::' . strtoupper('Charge' . 'd'))`

- Да, нет тестов, есть пробелы по phpdoc и декларации типов, ну и в реализации handler класса нет обработки стэйта, торопился, доделывал как всегда в последний момент :)

**Comment by manitu1983** [comment]
- сейчас есть дополнительная сущность Storage которая работает с конкретным адаптером, но мне не ясно чем хуже решение при котором MongoStorage/RedisStorage implements IStorage и реализуют этот интерфейс? Мне не очевидны плюсы использования адаптера здесь и сейчас.
При этом очевидно что добавляется новая абстракция, а абстракции усложняют код если не нужны.
- да array_diff не увидит разницы между 2 и '2', что вполне может привести к неочевидному багу если такое решение есть в дебрях проекта.

**Comment by g3co** [comment]
@manitu1983 да, здесь и сейчас адаптеры не к месту. Но допустим есть сущность юзер наследующий интерфейс iUser. При имплементации RedisStorage implements IStorage мы можем сохранить, допустим в редисе, только объект реализующий iPayment. Для сохранения новой сущности придётся задублировать код работы с хранилищем. В данном же случае потребуется создать класс аналог iStorage для юзера, подготавливающий данные для работы с хранилищем. 

Если другими словами, то Payment ничего не знает о хранилище и хранилище ничего не знает о Payment. И мне кажется, что это хорошо :)

**Comment by manitu1983** [comment]
- В process проверяешь action на наличие в state, а затем при создании платежа явно указываешь state:charged. Предложи вариант как более удобно работать со state без всяких мапперов на входе и defined, т.к. платежи нужно создавать с разными state, а не только charged.

- "Необходимости в лишних запросах нет (проверка существования и получение объекта), можно записать все поля сразу. Но чтобы вписаться в требования задачи". Так всё-таки есть необходимость в лишнем запросе или нет. Почему поставлены такие требования?

**Comment by g3co** [comment]
@manitu1983 

- Да с action == state была ошибка и переделал без мапперов, запушил новые изменения
- Если нет задачи писать только обновлённые данные то нет необходимости в лишних запросах, в моём случае нет необходимости в запросе storage->has(). Переделал на новый вариант.

**Comment by manitu1983** [comment]
- по-моему со стейтом хуже стало. Программа подменяет данные в эвенте, хотя должна их обрабатывать.
- это был сарказм, конечно, условия задачи в данном случае, являются определяющими. Я имею ввиду, что эти условия даны не просто так - лишнего запроса в базу на чтение быть не должно и при этом сохранять нужно только изменения.
- насчёт адаптера, всё таки ощущение что абстракция лишняя. Ну и для монго неплохо бы использовать более высокоуровневый интерфейс https://docs.mongodb.com/php-library/current/ .
Сторадж для монго и редиса скорее должен реализовывать интерфейс нужный программе, а не делать проброс через универсальные методы save/del/ итд в интерфейс либы для работы с базой. Должно было получиться что-то вроде paymentMongoStorage->save/get/getDeclined/getNewest(count=10). В этом paymentStorage получается ссылка на конкретную коллекцию в монго, которая уже предоставляет высокоуровневое api для работы с коллекцией.
Надо быть близко к реальным задачам и я не представляю когда бы мы захотели перевезти реальную коллекцию из монго в редис.
